services:
    postgres:
        container_name: jwt_postgres
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: jwtdb
        ports:
            - "5433:5432"
        volumes:
            - jwtvolume:/var/lib/postgresql
    app:
        container_name: spring-jwt-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - postgres

volumes:
    jwtvolume:

